from rsf.proj import *

#
# Make filter.rsf
#
Flow('filter',None,'spike n1=1000 k1=300 | bandpass fhi=2 phase=n')
 
#
# Make filter.vpl
#
Result('filter','wiggle clip=0.02 title="Welcome to Madagascar"')
 
#Flow('wavelet',
#     '../fetch/SEAM_wavelet_8ms.rsf ../fetch/SEAM_wavelet-g_8ms_hdr.rsf',
Result('wavelet','../fetch/SEAM_wavelet_8ms.rsf',
       '''
       wiggle clip clip=.02 title="SEAM_wavelet_8ms"
       ''')


for wavelet in ["SEAM_wavelet_8ms", 
                "SEAM_wavelet-g_8ms", 
		"SEAM_wavelet-g-zph_8ms", 
		"desig_8ms"] :
   Result(wavelet,'../fetch/'+wavelet+".rsf",
          'sfwiggle title=%s'%wavelet)

Flow('spike1',None,
     '''
     spike n1=256 k1=126 \
     | sfput d1=.008 
     ''')

Result('spike1','sfwindow min1=.8 max1=1.2 | sfwiggle title=spike1')


Flow('wave1.rsf wave1_hdr.rsf',
     'spike1.rsf ../fetch/SEAM_wavelet-g_8ms_hdr.rsf ../fetch/SEAM_wavelet-g_8ms.rsf',
     '''
     sftahread \
        input=${SOURCES[0]} \
	headers=${SOURCES[1]} \
	verbose=1 \
     | sftahfilter \
       verbose=3 \
       filter_file=${SOURCES[2]}
     | sftahwrite \
          output=${TARGETS[0]}
          label2="dt" o2=8000 n2=1 d2=1 \
	  verbose=1
     ''',stdout=0,stdin=0)
Result('wave1','sfwiggle title=wave1')

Flow('wave2.rsf wave2_hdr.rsf',
     'wave1.rsf wave1_hdr.rsf ../fetch/desig_8ms.rsf',
     '''
     sftahread \
        input=${SOURCES[0]} \
	headers=${SOURCES[1]} \
	verbose=1 \
     | sftahfilter \
       verbose=3 \
       filter_file=${SOURCES[2]}   \
       filt_indx_t0=84             \
     | sftahwrite \
          output=${TARGETS[0]}
          label2="dt" o2=8000 n2=1 d2=1 \
	  verbose=1
     ''',stdout=0,stdin=0)
Result('wave2','sfwindow min1=.8 max1=1.2 | sfwiggle title=wave2')

#-------------------------------------------------------------------------------
# Compute CDPs and Offsets window data by shot record (ep) and tracf key
# Output header values to text file
#-------------------------------------------------------------------------------

Flow(['ep','ep_hdr'],
     ['../fetch/shots-receivers-23900.rsf','../fetch/shots-receivers-23900_hdr.rsf'],
     '''
     sftahread \
       input=${SOURCES[0]} 
       verbose=1 \
     | sftahheadermath \
       outputkey=offset \
       output="abs(sx-gx)" \
     | sftahheadermath \
       outputkey=xline \
       output='(((sx+gx)*100)/2/125+5)/10' \
     | sftahheadermath outputkey=cdp output=xline \
     | sftahheadermath \
       outputkey=iline \
       output=1 \      
     | sftahgethw \
       key=tracr,tracf,ep,cdp,offset,gelev,selev,sdepth,scalel,scalco,sx,sy,gx,gy,ns,dt,grnlof,smeas4,smeasu,unass1,unass2 2>raw_hdr.txt \
     | sftahwrite \
       output=${TARGETS[0]} \
       label2="ep" o2=3041 n2=151 d2=81 \
       label3="tracf" o3=361 n3=901 d3=721 \
       verbose=1
     ''',stdout=0, stdin=0)

Plot('ep','sfgrey title=Fldr')

#-------------------------------------------------------------------------------
# Apply deterministic deconvolution via the filter provided with the seam data
#-------------------------------------------------------------------------------

Flow(['decon.rsf','decon_hdr.rsf'],
     ['ep','ep_hdr.rsf','../fetch/desig_8ms.rsf'],
     '''
     sftahread \
       input=${SOURCES[0]} \
       headers=${SOURCES[1]} \
       verbose=1 \
     | sftahfilter \
       verbose=3 \
       filter_file=${SOURCES[2]}
       filter_index_t0=84
     | sftahwrite \
       output=${TARGETS[0]}
       label2="ep" o2=3041 n2=151 d2=81 \
       label3="tracf" o3=361 n3=901 d3=721 \            
     ''',stdout=0,stdin=0)

Plot('decon','sfgrey title=Deconvolution')

End()




