from rsf.proj import *

#
# Make filter.rsf
#

#Flow('wavelet',
#     '../fetch/SEAM_wavelet_8ms.rsf ../fetch/SEAM_wavelet-g_8ms_hdr.rsf',
Result('wavelet','../fetch/SEAM_wavelet_8ms.rsf',
       '''
       wiggle clip clip=.02 title="SEAM_wavelet_8ms"
       ''')


for wavelet in ["SEAM_wavelet_8ms", 
                "SEAM_wavelet-g_8ms", 
		"SEAM_wavelet-g-zph_8ms", 
		"desig_8ms"] :
   Result(wavelet,'../fetch/'+wavelet+".rsf",
          'sfwiggle title=%s'%wavelet)

Flow('spike1',None,
     '''
     spike n1=256 k1=126 \
     | sfput d1=.008 
     ''')

Result('spike1','sfwindow min1=.8 max1=1.2 | sfwiggle title=spike1')


Flow('wave1.rsf wave1_hdr.rsf',
     'spike1.rsf ../fetch/SEAM_wavelet-g_8ms_hdr.rsf ../fetch/SEAM_wavelet-g_8ms.rsf',
     '''
     sftahread \
        input=${SOURCES[0]} \
	   headers=${SOURCES[1]} \
	   verbose=1 \
     | sftahfilter \
       verbose=3 \
       filter_file=${SOURCES[2]}
     | sftahwrite \
          output=${TARGETS[0]}
          label2="dt" o2=8000 n2=1 d2=1 \
	        verbose=1
     ''',stdout=0,stdin=0)
Result('wave1','sfwiggle title=wave1')

Flow('wave2.rsf wave2_hdr.rsf',
     'wave1.rsf wave1_hdr.rsf ../fetch/desig_8ms.rsf',
     '''
     sftahread \
       input=${SOURCES[0]} \
	     headers=${SOURCES[1]} \
	     verbose=1 \
     | sftahfilter \
       verbose=3 \
       filter_file=${SOURCES[2]}   \
       filt_indx_t0=84             \
     | sftahwrite \
          output=${TARGETS[0]}
          label2="dt" o2=8000 n2=1 d2=1 \
	  verbose=1
     ''',stdout=0,stdin=0)
Result('wave2','sfwindow min1=.8 max1=1.2 | sfwiggle title=wave2')

#-------------------------------------------------------------------------------
# Compute CDPs and Offsets window data by shot record (ep) and tracf key
# Output header values to text file
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Apply deterministic deconvolution via the filter provided with the seam data
#-------------------------------------------------------------------------------

Flow(['decon.rsf','decon_hdr.rsf'],
     ['../ntg/shots-receivers-23900_headfix.rsf','../ntg/shots-receivers-23900_headfix_hdr.rsf','../fetch/desig_8ms.rsf'],
     '''
     sftahread \
       input=${SOURCES[0]} \
       headers=${SOURCES[1]} \
       verbose=1 \
     | sftahfilter \
       verbose=1 \
       filter_file=${SOURCES[2]} \
       filt_indx_t0=84 \
     | sftahwrite \
       output=${TARGETS[0]}
       label2="gx" o2=0 n2=901 d2=25 \
       label3="sx" o3=3700 n3=161 d3=100 \   
     ''',stdout=0,stdin=0)

Plot('decon','sfgrey title=Deconvolution')

#-------------------------------------------------------------------------------
# Sort to NTG for comparison with raw data NTG
#-------------------------------------------------------------------------------

Flow(['ntgdecon.rsf','ntgdecon_hdr.rsf'],
     ['decon.rsf',  
      'decon_hdr.rsf'],
     '''
     sftahsort \
       input=${SOURCES[0]} \
       sort="cdp offset:0,200" \
       verbose=1 \
     | sftahmakeskey pkey=cdp skey=cdpt \
     | sftahgain tpow=1.5 verbose=1 \
     | sftahgethw \
         key=cdp,cdpt,offset 2>ntg_hdr.txt \
     | sftahwrite \
         output=${TARGETS[0]} \
         label2=cdp o2=148 n2=1501 d2=1 \
         label3=cdpt o3=1 n3=1 d3=1 \
         verbose=1
     ''',stdout=0, stdin=0)

Plot('ntgdecon','grey title=Near Trace Gather with Deconvolution') 


#-------------------------------------------------------------------------------
# Create figures for comparison with raw data
#-------------------------------------------------------------------------------
       
Result('ntgdecon',"sfgrey title='near trace gather'")

Result('ntgzoomdecon','ntgdecon',
  '''
  sfwindow min1=1.5 max1=4.5 \
  | sfgrey title='Near Trace Gather Deconvolution'
  ''')

Plot('ntgz1decon','ntgdecon',
  '''
  sfwindow min1=1.800 max1=2.096 \
  | sfgrey title='Near Trace Gather Deconvolution'
  ''')

Plot('ntgz2decon','ntgdecon',
  '''
  sfwindow min1=3.600 max1=4.192 \
  | sfgrey title='Near Trace Gather Deconvolution'
  ''')

Result('ntgdeconzoom2','ntgz1decon ntgz2decon','SideBySideAniso')

#-------------------------------------------------------------------------------
# Compare the data before and after deconvolution Raw Vs Decon
#-------------------------------------------------------------------------------

Result('ntgcomp','ntgdecon ../ntg/Fig/ntg.vpl','SideBySideAniso')

#-------------------------------------------------------------------------------
# Compare NTG zoom at different times and display with single trace from raw and
# Processed data
#-------------------------------------------------------------------------------

Result('ntgcomp_15_45','./Fig/ntgzoomdecon.vpl ../ntg/Fig/ntgzoom.vpl','SideBySideAniso')

Result('ntgcomp_175_225','ntgz1decon ../ntg/ntgz1.vpl','SideBySideAniso')

Result('ntgcomp_375_425','ntgz2decon ../ntg/ntgz2.vpl','SideBySideAniso')


Flow('cdp900_cdpt1','ntgdecon',
     '''
     sfwindow \
     min1=1.5 max1=4.5 \
     min2=900 max2=900 \
     min3=1 max3=1 \
     ''')

Plot('cdp900_cdpt1','sfgraph title=Dephase') 

End()




