#!/usr/bin/python
from rsf.proj import *


# -----------------------------------------------------------------------------------------------------------
# Capture a single CDP900 
# Ex. /home/jeff/madagascar/book/rsf/su/rsflab16 
# When queried actual header values such as cdp are not reatining their values i.e. cdp900
# is listed as 148 however all the traces are there.
# -----------------------------------------------------------------------------------------------------------

for key in ('cdp','offset'):
    Flow(key,'../iva/cdp_hdr.rsf','dd type=float | headermath output=%s' % key)

Flow('cdpmask','cdp','mask min=900 max=900')

Flow('cdp900','../iva/cdp.rsf cdpmask',
     '''
     headerwindow mask=${SOURCES[1]} 
     ''')       

Flow('offset900','offset cdpmask',
     'headerwindow mask=${SOURCES[1]}')
Plot('offset900','grey')

Plot('cdp900','sfgrey title="CDP 900" label2=Trace')

# -----------------------------------------------------------------------------------------------------------
# Check frequency spectrum to formulate tau-p parameters
# -----------------------------------------------------------------------------------------------------------

spectra = []
for case in Split('cdp900'):
    Flow(case+'-spectra',case,'spectra all=y')
    spectra.append(case+'-spectra')

Result('spectra',spectra,
       ''' 
       scale axis=1 | 
       window max1=50 |
       graph title=Spectra dash=0,5 plotcol=6,5 label2="Amplitude"
       ''')

# -----------------------------------------------------------------------------------------------------------
# VSCAN no filter
# Attempting to pick some prelminary primary velocites with sfipick, at the present time 
# Using sfimage with .rsf file and printing the results to the terminal screen with sftahnmo
# have been my best results. Auto pick does not create the necessary movemout to allow for
# clear differentiation betweer the two waves.
# -----------------------------------------------------------------------------------------------------------

Flow('vscan1','cdp900 offset900',
'''
vscan semblance=y half=n nv=125 v0=1300 dv=25 offset=${SOURCES[1]}\
''')

# -----------------------------------------------------------------------------------------------------------
# Create Velocity function from picks vscan1
# -----------------------------------------------------------------------------------------------------------

tnmo=(2.54102,4.17997,4.84064,5.18367,5.66647,5.83163,6.06033,6.82263,6.93698,7.25460)
vnmo=(1543.06,2296.53,1822.92,1930.56,2210.42,2597.92,2684.03,3329.86,4298.61,4427.78)

Flow('cdp900vpick.asc',None,
     '''
     echo %s n1=%d n2=2 data_format=ascii_float in=$TARGET
     ''' % (' '.join(map(str,tnmo)+map(str,vnmo)),len(tnmo)))
Flow('cdp900vel','cdp900vpick.asc cdp900',
     'dd form=native | linear pattern=${SOURCES[1]}') # rect=5 niter=100')


Plot('vscan1','grey color=j allpos=y title="CDP 900 Vscan" unit2=m/s')

Plot('cdp900vel',
'''
graph yreverse=y transp=y plotcol=0 plotfat=7
pad=n min2=1300 max2=4500 wantaxis=n wanttitle=n
''')

Plot('vscan1pick','vscan1 cdp900vel','Overlay')

# -----------------------------------------------------------------------------------------------------------
# NMO with initial best guess primaries
# -----------------------------------------------------------------------------------------------------------

Flow('cdp900nmo','cdp900 offset900 cdp900vel',
     '''
     nmo half=n offset=${SOURCES[1]} velocity=${SOURCES[2]} 
     ''')

Plot('cdp900nmo','sfgrey title="CDP 900 NMO" label2="Trace"')

# -----------------------------------------------------------------------------------------------------------
# Slant Stack
# Using the sftahnmo cdp I've used the sfslant program to change the data to the taup domain.
# In this example I've used the sfcut program to isolate the signal
# -----------------------------------------------------------------------------------------------------------

Flow('slant','cdp900nmo offset900','slant adj=y p0=-.003 np=80 dp=.001 offset=${SOURCES[1]}')
Plot('slant','sfgrey color=j title=Slantstack label2=p')

# -----------------------------------------------------------------------------------------------------------
# Design mute for mutiples in the taup domain MAY NOT USE
# -----------------------------------------------------------------------------------------------------------

Flow('slantcut','slant','cut min2=.001 min1=1.75')
Plot('slantcut','sfgrey color=j title="Preserve Primaries" label2=p')

Flow('signal','slantcut',
     '''
     slant adj=n x0=15100 dx=1 nx=151 
     ''')
Plot('signal','sfgrey color=j')
# -----------------------------------------------------------------------------------------------------------
# INMO requires offset=${SOURCES[1]} velocity=${SOURCES[2]} in that order or the moveout will not work properly.
# Subtract muliples and creat new Vscan
# -----------------------------------------------------------------------------------------------------------

Flow('primary','signal offset900 cdp900vel',
     '''
     inmo half=n offset=${SOURCES[1]} velocity=${SOURCES[2]} 
     | mutter v0=1500 t0=2 offset=${SOURCES[1]} 
     | put o2=1 n2=151 d2=1
     ''')
Plot('primary','sfgrey title="CDP 900 Filtered" label2=Trace')

Flow('vscan2','primary offset900',
'''
vscan semblance=y half=n nv=125 nb=2 v0=1500 dv=25 weighted=y offset=${SOURCES[1]}
| cut max1=2
''')

Plot('vscan2','grey color=j allpos=n title="CDP 900 Vscan Filtered" unit2=m/s')

# -----------------------------------------------------------------------------------------------------------
# Automatic pick
# -----------------------------------------------------------------------------------------------------------

Flow('vpick2','vscan2',
'''
pick rect1=250 rect2=250 vel0=1500 an=2 smooth=n an=75 gate=10
''')

Plot('vpick2',
'''
graph yreverse=y transp=y plotcol=0 plotfat=7
pad=n min2=1300 max2=4500 wantaxis=n wanttitle=n
''')

# -----------------------------------------------------------------------------------------------------------
# VSCAN with auto pick
# -----------------------------------------------------------------------------------------------------------

Plot('vscan2pick','vscan2 vpick2','Overlay')

Flow('cdp900filt','primary offset900 vpick2',
     '''
     nmo half=n offset=${SOURCES[1]} velocity=${SOURCES[2]} 
     | mutter v0=1500 t0=1.75 offset=${SOURCES[1]} 
     | put o2=1 n2=151 d2=1
     ''')
Plot('cdp900filt','grey title="CDP 900 Filterd NMO" label2="Trace"')

Result('Compare','cdp900 vscan1pick cdp900nmo','SideBySideAniso')
Result('Compareb','slant slantcut signal','SideBySideAniso')
Result('Comparec','primary vscan2pick cdp900filt','SideBySideAniso')

End()

 
