#!/usr/bin/python
from rsf.proj import *

# -----------------------------------------------------------------------------------------------------------
# Capture a single CDP900 
# Ex. madagascar/book/rsf/su/rsflab16 
# When queried actual header values such as cdp are not reatining their values i.e. cdp900
# is listed as 148 however all the traces are there.
# -----------------------------------------------------------------------------------------------------------

for key in ('cdp','offset'):
    Flow(key,'../../iva/cdp_hdr.rsf','dd type=float | headermath output=%s' % key)

Flow('cdpmask','cdp','mask min=900 max=900')

Flow('cdp900','../../iva/cdp.rsf cdpmask',
     '''
     headerwindow mask=${SOURCES[1]} 
     ''')   

Plot('cdp900','sfgrey title="CDP 900" label2=Trace')

Flow('cdp900win','cdp900','window min1=3.25 max1=4')    
Plot('cdp900win','sfgrey title="CDP 900 Zoom" label2=offset')

# -----------------------------------------------------------------------------------------------------------
# Create offset file for cdp900
# -----------------------------------------------------------------------------------------------------------

Flow('offset900','offset cdpmask',
     'headerwindow mask=${SOURCES[1]}')
Plot('offset900','grey')

# -----------------------------------------------------------------------------------------------------------
# Check frequency spectrum for tau-p parameters
# -----------------------------------------------------------------------------------------------------------

spectra = []
for case in Split('cdp900'):
    Flow(case+'-spectra',case,'spectra all=y')
    spectra.append(case+'-spectra')

Plot('spectra',spectra,
       ''' 
       scale axis=1 | 
       window max1=50 |
       graph title=Spectra dash=0,5 plotcol=6,5 label2="Amplitude"
       ''')

# -----------------------------------------------------------------------------------------------------------
# VSCAN no filter
# Attempting to pick some prelminary primary velocites with sfipick, at the present time 
# Using sfimage with .rsf file and printing the results to the terminal screen with sftahnmo
# have been my best results. Auto pick does not create the necessary movemout to allow for
# clear differentiation betweer the two waves.
# -----------------------------------------------------------------------------------------------------------

Flow('vscan1','cdp900 offset900',
'''
vscan semblance=y half=n nv=125 v0=1300 dv=25 offset=${SOURCES[1]}\
''')
Plot('vscan1','grey color=j allpos=y title="CDP 900 Vscan" unit2=m/s')

# -----------------------------------------------------------------------------------------------------------
# Create Velocity functions for NMO tests with water velocity and user picks
# -----------------------------------------------------------------------------------------------------------

Flow('watervel','cdp900','window n2=1 | math output=1500')

# Karls | sftahnmo tnmo=0,2,6,10.5,16 vnmo=1500,1500,2250,3250,3700 \

tnmo=(0,2,6,10.5,16)
vnmo=(1500,1500,2250,3250,3700)

Flow('cdp900vpick.asc',None,
     '''
     echo %s n1=%d n2=2 data_format=ascii_float in=$TARGET
     ''' % (' '.join(map(str,tnmo)+map(str,vnmo)),len(tnmo)))

Flow('cdp900vel','cdp900vpick.asc cdp900',
     'dd form=native | linear pattern=${SOURCES[1]}') # rect=5 niter=100')
Plot('cdp900vel',
'''
graph yreverse=y transp=y plotcol=0 plotfat=7
pad=n min2=1300 max2=4500 wantaxis=n wanttitle=n
''')

# -----------------------------------------------------------------------------------------------------------
# Plot the user picks from the unfilterd cdp900 vscan
# -----------------------------------------------------------------------------------------------------------

Plot('vscan1pick','vscan1 cdp900vel','Overlay')

# -----------------------------------------------------------------------------------------------------------
# NMO with water velocity
# -----------------------------------------------------------------------------------------------------------

Flow('waternmo','cdp900 offset900 watervel',
     'nmo half=n offset=${SOURCES[1]} velocity=${SOURCES[2]}')
Plot('waternmo','grey title="CDP900 WNMO Velocity" label2="Offset"')

Flow('waternmowin','waternmo','window min1=3.25 max1=4')    
Plot('waternmowin','grey title="CDP900 WNMO Velocity Zoom" label2="Offset"')

# -----------------------------------------------------------------------------------------------------------
# NMO with user picks
# -----------------------------------------------------------------------------------------------------------

Flow('cdp900UPnmo','cdp900 offset900 cdp900vel',
     '''
     nmo half=n offset=${SOURCES[1]} velocity=${SOURCES[2]} 
     ''')
Plot('cdp900UPnmo','grey title="CDP900 UPNMO" label2="Trace"')

Flow('cdp900UPnmowin','cdp900nmo','window min1=3.25 max1=4')    
Plot('cdp900UPnmowin','grey title="CDP900 WNMO Velocity Zoom" label2="Offset"')

# -----------------------------------------------------------------------------------------------------------
# Radon transform
# In this example I've used the sfcut program to isolate the signal
# res moveout 400 ms set 500 ms for p value range try starting at -100 ms maybe far offset = 15100
# max imput data frequency is 50-60 Hz P-values= 2 parbs/Hz * 50 hz(cycles per sec) = 100 parabs/s
# delta t = 300 ms ; 100 parabs/1000ms*500ms=50 parabs
# p0=-.1 dp=.0016 np=50 
# -----------------------------------------------------------------------------------------------------------

# -----------------------------------------------------------------------------------------------------------
# Userpick Radon
# -----------------------------------------------------------------------------------------------------------

Flow('radonUP','cdp900nmo',
     '''
     radon adj=y spike=n parab=y p0=-.1 dp=.01 np=50  
     ''')
Plot('radonUP','grey title="CDP900 Radon Transform" label2="P"')

Flow('radonUPwin','radonUP','window min1=3.25 max1=4')    
Plot('radonUPwin','grey color=j gainpanel=a title="CDP 900 Zoom" label2=offset')

# -----------------------------------------------------------------------------------------------------------
# Water Velocity Radon
# -----------------------------------------------------------------------------------------------------------

Flow('radonW','waternmo',
     '''
     radon adj=y spike=n parab=y p0=-.1 dp=.01 np=50  
     ''')
Plot('radonW','grey title="CDP900 Water Radon Transform" label2="P"')

Flow('radonWwin','radonW','window min1=3.25 max1=4')    
Plot('radonWwin','grey color=j gainpanel=a title="CDP 900 Zoom" label2=offset')

# -----------------------------------------------------------------------------------------------------------
# Extract multiples from the data and perform inversion userp pick data
# -----------------------------------------------------------------------------------------------------------

Flow('radoncutW','radonW','cut min1=1.75 max2=0')
Plot('radoncutW','grey title="CDP900 Radon Transform water" label2="P"')

Flow('radoncutinvW','radoncutW offset900',
     '''
     radon adj=n parab=n nx=151 x0=15100 offset=${SOURCES[1]} 
     ''')
Plot('radoncutinvW','grey title="CDP900 Radon Inversion Water" label2="P"')

#Flow('rad900winUP','radon','window min1=3.25 max1=4')    
#Plot('rad900winUP','grey title="CDP 900slant Zoom" color=j label2=offset')

# -----------------------------------------------------------------------------------------------------------
# Protect multiples from the data and perform inversion water velocity
# -----------------------------------------------------------------------------------------------------------


#Result('Compared','cdp900win waternmo slantwin slant900win','SideBySideAniso')

# -----------------------------------------------------------------------------------------------------------
# Inverse NMO on the filtered cdp & velocity analysis from UPNMO
# INMO requires offset=${SOURCES[1]} velocity=${SOURCES[2]} in that order or the moveout will not work properly.
# -----------------------------------------------------------------------------------------------------------

Flow('primary','radoncutinvUP offset900 cdp900vel',
     '''
     inmo half=n offset=${SOURCES[1]} velocity=${SOURCES[2]} 
     | put o2=1 d2=1
     ''')
Plot('primary','sfgrey title="CDP900UP Filtered" label2=Trace')

Flow('vscan2','primary offset900',
     '''
     vscan semblance=y half=n nv=125 v0=1500 dv=25  offset=${SOURCES[1]}
     ''')
Plot('vscan2','grey color=j allpos=n title="CDP 900 Vscan Filtered" unit2=m/s')

# -----------------------------------------------------------------------------------------------------------
# INMO water velocity radon
# -----------------------------------------------------------------------------------------------------------

Flow('multiple','radoncutinvW offset900 cdp900vel',
     '''
     inmo half=n offset=${SOURCES[1]} velocity=${SOURCES[2]} 
     | put o2=1 d2=1
     ''')
Plot('multiple','sfgrey title="CDP 900 Water Filtered" label2="offset"')

Flow('vscan3','multiple offset900',
     '''
     vscan semblance=y half=n nv=125 v0=1500 dv=25  offset=${SOURCES[1]}
     ''')
Plot('vscan3','grey color=j allpos=n title="CDP 900 Vscan Filtered" unit2=m/s')

# -----------------------------------------------------------------------------------------------------------
# Automatic pick user picks
# -----------------------------------------------------------------------------------------------------------

Flow('vpick3','vscan3',
     '''
     pick rect1=250 rect2=250 vel0=1500 an=2 smooth=n an=75 gate=10
     ''')

Plot('vpick3',
     '''
     graph yreverse=y transp=y plotcol=0 plotfat=7
     pad=n min2=1300 max2=4500 wantaxis=n wanttitle=n
     ''')

Plot('vscan3pick','vscan3 vpick3','Overlay')

# -----------------------------------------------------------------------------------------------------------
# NMO with cdp UPNMO clean radon
# -----------------------------------------------------------------------------------------------------------

Flow('cdp900cleanW','multiple offset900 vpick3',
     '''
     nmo half=n offset=${SOURCES[1]} velocity=${SOURCES[2]} 
     | mutter v0=1500 t0=1.75 offset=${SOURCES[1]} 
     ''')
Plot('cdp900cleanW','grey title="CDP900 Filterd UPNMO" label2="Offset"')

# -----------------------------------------------------------------------------------------------------------
# NMO with cdp water NMO clean radon
# -----------------------------------------------------------------------------------------------------------

Flow('cdp900cleanUP','primary offset900 vpick2',
     '''
     nmo half=n offset=${SOURCES[1]} velocity=${SOURCES[2]} 
     | mutter v0=1500 t0=1.75 offset=${SOURCES[1]} 
     ''')
Plot('cdp900cleanUP','grey title="CDP900 Filterd UPNMO" label2="Offset"')

# -----------------------------------------------------------------------------------------------------------
# Images from userpick NMO
# -----------------------------------------------------------------------------------------------------------

Result('Compare','cdp900 vscan1pick waternmo cdp900UPnmo','SideBySideAniso')
Result('Compareb','radonUP radonUPwin radoncutUP radoncutinvUP','SideBySideAniso')
Result('Comparec','primary vscan2pick cdp900cleanUP','SideBySideAniso')

# -----------------------------------------------------------------------------------------------------------
# Images from water NMO
# -----------------------------------------------------------------------------------------------------------

Result('Compared','radonW radonWwin radoncutW radoncutinvW','SideBySideAniso')
Result('Comparee','multiple vscan3pick cdp900cleanW','SideBySideAniso')

# -----------------------------------------------------------------------------------------------------------
# Subtract multiples from original cdp
# -----------------------------------------------------------------------------------------------------------

Flow('cdp900filta','cdp900 multiple','add scale=1,-1 ${SOURCES[1]}')
Plot('cdp900filta','grey title="Multiples subtracted from raw data"')

Result('Comparef','cdp900 primary cdp900filta','SideBySideAniso')


End()

 
