#!/usr/bin/env python
from rsf.proj import *
import math


# Apply deterministic deconvolution via the filter provided with the seam data
#-------------------------------------------------------------------------------

Flow(['ep_sort_dp.rsf','ep_sort_dp_hdr.rsf'],
     ['../fldr/ep_sort.rsf','../fldr/ep_sort_hdr.rsf','desig_8ms.rsf'],
     '''
     sftahread \
       input=${SOURCES[0]} \
	     headers=${SOURCES[1]} \
	     verbose=1 \
     | sftahfilter \
       verbose=3 \
       filter_file=${SOURCES[2]}
       filter_index_t0=84
     | sftahwrite \
       output=${TARGETS[0]}
       label2="ep" o2=3041 n2=151 d2=81 \
       label3="tracf" o3=361 n3=901 d3=721 \
     ''',stdout=0,stdin=0)

Plot('ep_sort_dp','sfgrey')

# Extract the same trace from the ep with the deconvolution applied
# Can extract 1st and apply decon without applyin to all data
# 
# check the scale for the sfgraph check
#-------------------------------------------------------------------------------

Flow('ep3041_dp','ep_sort_dp',
     '''
     sfwindow \
     min1=5 max1=7 \
     min2=3041 max2=3041 \
     min3=361 max3=361 \
     ''')

# Compare the traces before and after deconvolution
#-------------------------------------------------------------------------------

Plot('tracf361_dp','ep3041_dp','sfgraph title="Dephase" symbol=. symbolsz=8') 

#Result('ep_dp_comp','tracf361 tracf361_dp','Overlay')

#Sort to NTG and comapre with Karls images
#-------------------------------------------------------------------------------
Flow(['ntg_dp.rsf','ntg_dp_hdr.rsf'],
     ['/home/jeff/seam/ntg/ntg.rsf','/home/jeff/seam/ntg/ntg_hdr.rsf','desig_8ms.rsf'],
     '''
     sftahread \
        input=${SOURCES[0]} \
	headers=${SOURCES[1]} \
	verbose=1 \
     | sftahfilter \
       verbose=3 \
       filter_file=${SOURCES[2]}
       filter_index_t0=84
     | sftahwrite \
       output=${TARGETS[0]}
       label2=cdp o2=148 n2=1501 d2=1 \
       label3=cdpt o3=1 n3=1 d3=1 \
     ''',stdout=0,stdin=0)

Plot('ntg_dp','sfgrey')
Result('ntg_comp','ntg_dp /home/jeff/seam/ntg/Fig/ntg','SideBySideAniso')

 

#seam/processing/decon

End()

