#!/usr/bin/python
from rsf.proj import *

# -----------------------------------------------------------------------------------------------------------
# Capture a single CDP900 
# Ex. madagascar/book/rsf/su/rsflab16 
# When queried actual header values such as cdp are not reatining their values i.e. cdp900
# is listed as 148 however all the traces are there.
# -----------------------------------------------------------------------------------------------------------

for key in ('cdp','offset'):
    Flow(key,'../../iva/cdp_hdr.rsf','dd type=float | headermath output=%s' % key)

Flow('cdpmask','cdp','mask min=900 max=900')

Flow('cdp900','../../iva/cdp.rsf cdpmask',
     '''
     headerwindow mask=${SOURCES[1]} 
     ''')   

Plot('cdp900','sfgrey title="CDP 900" label2=Trace')

Flow('cdp900win','cdp900','window min1=3.25 max1=4')    
Plot('cdp900win','sfgrey title="CDP 900 Zoom" label2=offset')

# -----------------------------------------------------------------------------------------------------------
# Create offset file for cdp900
# -----------------------------------------------------------------------------------------------------------

Flow('offset900','offset cdpmask',
     'headerwindow mask=${SOURCES[1]}')
Plot('offset900','grey')

# -----------------------------------------------------------------------------------------------------------
# Check frequency spectrum to formulate tau-p parameters
# -----------------------------------------------------------------------------------------------------------

spectra = []
for case in Split('cdp900win'):
    Flow(case+'-spectra',case,'spectra all=y')
    spectra.append(case+'-spectra')

Plot('spectra',spectra,
       ''' 
       scale axis=1 | 
       window max1=50 |
       graph title=Spectra dash=0,5 plotcol=6,5 label2="Amplitude"
       ''')

# -----------------------------------------------------------------------------------------------------------
# VSCAN no filter
# Attempting to pick some prelminary primary velocites with sfipick, at the present time 
# Using sfimage with .rsf file and printing the results to the terminal screen with sftahnmo
# have been my best results. Auto pick does not create the necessary movemout to allow for
# clear differentiation betweer the two waves.
# -----------------------------------------------------------------------------------------------------------

Flow('vscan1','cdp900 offset900',
'''
vscan semblance=y half=n nv=125 v0=1300 dv=25 offset=${SOURCES[1]}\
''')

# -----------------------------------------------------------------------------------------------------------
# Create Velocity functions for NMO tests with water velocity and user picks
# -----------------------------------------------------------------------------------------------------------

Flow('watervel','cdp900','window n2=1 | math output=1500')

#tnmo=(2.54102,4.17997,4.84064,5.18367,5.66647,5.83163,6.06033,6.82263,6.93698,7.25460)
#vnmo=(1543.06,2296.53,1822.92,1930.56,2210.42,2597.92,2684.03,3329.86,4298.61,4427.78)

# Karls | sftahnmo tnmo=0,2,6,10.5,16 vnmo=1500,1500,2250,3250,3700 \
# Karls picks produce the better results!!
# nmo=0,2,6,10.5,16 vnmo=1500,1500,2250,3250,3700 \

tnmo=(0,2,6,10.5,16)
vnmo=(1500,1500,2250,3250,3700)
#vnmo=(1500,1500,2250,3250,3700)

Flow('cdp900vpick.asc',None,
     '''
     echo %s n1=%d n2=2 data_format=ascii_float in=$TARGET
     ''' % (' '.join(map(str,tnmo)+map(str,vnmo)),len(tnmo)))
Flow('cdp900vel','cdp900vpick.asc cdp900',
     'dd form=native | linear pattern=${SOURCES[1]}') # rect=5 niter=100')


Plot('vscan1','grey color=j allpos=y title="CDP 900 Vscan" unit2=m/s')

Plot('cdp900vel',
'''
graph yreverse=y transp=y plotcol=0 plotfat=7
pad=n min2=1300 max2=4500 wantaxis=n wanttitle=n
''')

Plot('vscan1pick','vscan1 cdp900vel','Overlay')

# -----------------------------------------------------------------------------------------------------------
# NMO with water velocity
# -----------------------------------------------------------------------------------------------------------

Flow('waternmo','cdp900 offset900 watervel',
     'nmo half=n offset=${SOURCES[1]} velocity=${SOURCES[2]}')
Plot('waternmo','sfgrey title="Water NMO" label2="Trace"')

Flow('waternmowin','waternmo','window min1=3.25 max1=4')    
Plot('waternmowin','sfgrey title="CDP 900waternmo Zoom" label2=offset')

# -----------------------------------------------------------------------------------------------------------
# NMO with user picks
# -----------------------------------------------------------------------------------------------------------

Flow('cdp900UPnmo','cdp900 offset900 cdp900vel',
     '''
     nmo half=n offset=${SOURCES[1]} velocity=${SOURCES[2]} 
     ''')

Plot('cdp900UPnmo','sfgrey title="CDP 900 NMO" label2="Trace"')

# -----------------------------------------------------------------------------------------------------------
# Slant Stack
# Using the sftahnmo cdp I've used the sfslant program to change the data to the taup domain.
# In this example I've used the sfcut program to isolate the signal
# res moveout 400 ms set 500 ms for p value range try starting at 100 ms maybe
# far offset = 15100
# max imput data frequency is 50 Hz P-values= 2 parbs/Hz * 50 hz(cycles per sec) = 100 parabs/s
# delta t = 300 ms ; 100 parabs/1000ms*500ms=50 parabs
# -----------------------------------------------------------------------------------------------------------

# -----------------------------------------------------------------------------------------------------------
# Water slant stack processing
# -----------------------------------------------------------------------------------------------------------

Flow('slantW','waternmo offset900',
     '''
     slant adj=y p0=-.001 np=65 dp=.0001 offset=${SOURCES[1]}
     ''')
Plot('slantW','sfgrey title="CDP900W slant" color=j label2=offset')

Flow('slantcutW','slantW',
     '''
     cut min1=0 max2=0
     ''')
Plot('slantcutW','grey title="CDP900W slant cut" color=j label2=offset')

Flow('slantcutinvW','slantcutW',
     '''
     slant adj=n x0=100 dx=100 nx=151
     ''')
Plot('slantcutinvW','grey title="CDP900W slant cut inversion" color=j label2=offset')

# -----------------------------------------------------------------------------------------------------------
# Userpick slant stack processing
# -----------------------------------------------------------------------------------------------------------

Flow('slantUP','cdp900UPnmo offset900',
     '''
     slant adj=y p0=-.001 np=65 dp=.0001 offset=${SOURCES[1]}
     ''')
Plot('slantUP','sfgrey title="CDP900UP slant" color=j label2=offset')

Flow('slantcutUP','slantUP',
     '''
     cut min1=0 max2=0
     ''')
Plot('slantcutUP','sfgrey title="CDP900UP slant cut" color=j label2=offset')


Flow('slantcutinvUP','slantcutUP',
     '''
     slant adj=n x0=100 dx=100 nx=151
     ''')
Plot('slantcutinvUP','grey title="CDP900UP slant cut inversion" color=j label2=offset')

# -----------------------------------------------------------------------------------------------------------
# INMO requires offset=${SOURCES[1]} velocity=${SOURCES[2]} in that order or the moveout will not work properly.
# Subtract muliples and creat new Vscan x0=100 dx=200 nx=75 
# -----------------------------------------------------------------------------------------------------------

Flow('primary','slantcutinvUP offset900 cdp900vel',
     '''
     inmo half=n offset=${SOURCES[1]} velocity=${SOURCES[2]} 
     | put o2=1 d2=1
     ''')
Plot('primary','sfgrey title="CDP900UP Filtered" label2=Trace')

Flow('multiple','slantcutinvW offset900 watervel',
     '''
     inmo half=n offset=${SOURCES[1]} velocity=${SOURCES[2]} 
     | put o2=1 d2=1
     ''')
Plot('multiple','sfgrey title="CDP900UP Filtered" label2=Trace')

# -----------------------------------------------------------------------------------------------------------
# Velocity Scan
# -----------------------------------------------------------------------------------------------------------

Flow('vscan2','primary offset900',
'''
vscan semblance=y half=n nv=125 v0=1500 dv=25  offset=${SOURCES[1]}
''')
Plot('vscan2','grey color=j allpos=n title="CDP 900 Vscan Filtered" unit2=m/s')

Flow('vscan3','multiple offset900',
'''
vscan semblance=y half=n nv=125 v0=1500 dv=25  offset=${SOURCES[1]}
''')
Plot('vscan3','grey color=j allpos=n title="CDP 900 Vscan Filtered" unit2=m/s')

# -----------------------------------------------------------------------------------------------------------
# Automatic pick
# -----------------------------------------------------------------------------------------------------------

Flow('vpick2','vscan2',
'''
pick rect1=250 rect2=250 vel0=1500 an=2 smooth=n an=75 gate=10
''')

Plot('vpick2',
'''
graph yreverse=y transp=y plotcol=0 plotfat=7
pad=n min2=1300 max2=4500 wantaxis=n wanttitle=n
''')

Flow('vpick3','vscan3',
'''
pick rect1=250 rect2=250 vel0=1500 an=2 smooth=n an=75 gate=10
''')

Plot('vpick3',
'''
graph yreverse=y transp=y plotcol=0 plotfat=7
pad=n min2=1300 max2=4500 wantaxis=n wanttitle=n
''')

Plot('vscan2pick','vscan2 vpick2','Overlay')

Plot('vscan3pick','vscan3 vpick3','Overlay')

# -----------------------------------------------------------------------------------------------------------
# VSCAN NMO with auto picks 
# -----------------------------------------------------------------------------------------------------------

Flow('cdp900cleanUP','primary offset900 vpick2',
     '''
     nmo half=n offset=${SOURCES[1]} velocity=${SOURCES[2]} 
     ''')
Plot('cdp900cleanUP','grey title="CDP900UP Filterd NMO" label2="Trace"')

Flow('cdp900cleanW','multiple offset900 vpick3',
     '''
     nmo half=n offset=${SOURCES[1]} velocity=${SOURCES[2]} 
     ''')
Plot('cdp900cleanW','grey title="CDP900UP Filterd NMO" label2="Trace"')

# -----------------------------------------------------------------------------------------------------------
# Images from userpick NMO
# -----------------------------------------------------------------------------------------------------------

Result('Compare','cdp900 vscan1pick waternmo cdp900UPnmo','SideBySideAniso')
Result('Compareb','slantUP slantcutUP slantcutinvUP','SideBySideAniso')
Result('Comparec','primary vscan2pick cdp900cleanUP','SideBySideAniso')

# -----------------------------------------------------------------------------------------------------------
# Images from water NMO
# -----------------------------------------------------------------------------------------------------------

Result('Compared','slantW slantcutW slantcutinvW','SideBySideAniso')
Result('Comparee','multiple vscan3pick cdp900cleanW','SideBySideAniso')

# -----------------------------------------------------------------------------------------------------------
# Subtract multiples from original cdp
# -----------------------------------------------------------------------------------------------------------

Flow('cdp900filta','cdp900 multiple','add scale=1,-1 ${SOURCES[1]}')
Plot('cdp900filta','grey title="Multiples subtracted from raw data"')

Result('Comparef','cdp900 primary cdp900filta','SideBySideAniso')

End()



