#!/usr/bin/python
from rsf.proj import *

#-------------------------------------------------------------------------------
# Compute CDPs and Offsets window data by shot record (ep) and tracf key
# Output header values to text file
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Apply deterministic deconvolution via the filter provided with the seam data 
# to the entire dataset
#-------------------------------------------------------------------------------

Flow(['decon.rsf','decon_hdr.rsf'],
     ['../../ntg/shots-receivers-23900_headfix.rsf','../../ntg/shots-receivers-23900_headfix_hdr.rsf','../../fetch/desig_8ms.rsf'],
     '''
     sftahread \
       input=${SOURCES[0]} \
        headers=${SOURCES[1]} \
       verbose=1 \
     | sftahfilter \
       verbose=3 \
       filter_file=${SOURCES[2]}
       filter_index_t0=0
       verbose=1 \
       filter_file=${SOURCES[2]} \
       filt_indx_t0=84 \
     | sftahwrite \
       output=${TARGETS[0]}
       label2="gx" o2=0 n2=901 d2=25 \
       label3="sx" o3=3700 n3=161 d3=100 \   
     ''',stdout=0,stdin=0)

Plot('decon','sfgrey title=Deconvolution')

#-------------------------------------------------------------------------------
# Sort to NTG for comparison with raw data NTG
#-------------------------------------------------------------------------------

Flow(['ntgdecon.rsf','ntgdecon_hdr.rsf'],
     ['decon.rsf',  
      'decon_hdr.rsf'],
     '''
     sftahsort \
       input=${SOURCES[0]} \
       sort="cdp offset:0,200" \
       verbose=1 \
     | sftahmakeskey pkey=cdp skey=cdpt \
     | sftahgain tpow=1.5 verbose=1 \
     | sftahgethw \
         key=cdp,cdpt,offset 2>ntg_hdr.txt \
     | sftahwrite \
         output=${TARGETS[0]} \
         label2=cdp o2=148 n2=1501 d2=1 \
         label3=cdpt o3=1 n3=1 d3=1 \
         verbose=1
     ''',stdout=0, stdin=0)

Plot('ntgdecon','grey title=Near Trace Gather with Deconvolution') 


#-------------------------------------------------------------------------------
# Create figures for comparison with raw data
#-------------------------------------------------------------------------------
       
Result('ntgdecon',"sfgrey title='near trace gather'")

Result('ntgzoomdecon','ntgdecon',
  '''
  sfwindow min1=1.5 max1=4.5 \
  | sfgrey title='Near Trace Gather Deconvolution'
  ''')

Plot('ntgz1decon','ntgdecon',
  '''
  sfwindow min1=1.75 max1=2.25 \
  sfwindow min1=1.800 max1=2.096 \
  | sfgrey title='Near Trace Gather Deconvolution'
  ''')

Plot('ntgz2decon','ntgdecon',
  '''
  sfwindow min1=3.75 max1=4.25 \
  sfwindow min1=3.600 max1=4.192 \
  | sfgrey title='Near Trace Gather Deconvolution'
  ''')


Result('ntgdeconzoom2','ntgz1decon ntgz2decon','SideBySideAniso')

#-------------------------------------------------------------------------------
# Compare the data before and after deconvolution Raw Vs Decon
#-------------------------------------------------------------------------------

Result('ntgcomp','ntgdecon ../ntg/Fig/ntg.vpl','SideBySideAniso')

#-------------------------------------------------------------------------------
# Compare NTG zoom at different times and display with single trace from raw and
# Processed data
#-------------------------------------------------------------------------------

Result('ntgcomp_15_45','./Fig/ntgzoomdecon.vpl ../ntg/Fig/ntgzoom.vpl','SideBySideAniso')

Result('ntgcomp_175_225','ntgz1decon ../../ntg/ntgz1.vpl','SideBySideAniso')

Result('ntgcomp_375_425','ntgz2decon ../../ntg/ntgz2.vpl','SideBySideAniso')


Flow('cdp900_cdpt1','ntgdecon',
     '''
     sfwindow \
     min1=1.5 max1=4.5 \
     min2=900 max2=900 \
     min3=1 max3=1 \
     ''')

Plot('cdp900_cdpt1','sfgraph title=Dephase') 

End()




